Clean-mymdb-client
ibxibx/mymdb pull request #10
Opened 2024-08-12 21:40 UTC by ibxibx

Pull Request 10 with clean code

2024-08-12 22:33 UTC, stratospherique requested changes

2024-08-12 22:33 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +            director: movie.Director.Name,
Going back to the API project. Since you choose to have the director and genre as a seperate collection that gets referenced in the movie collection using their respective IDS, when you pull a movie object you get an attribute called DirectorID that doesn't have a nested attribute called name. The DirectorID is a string and not an object. The same goes for the GenreID. You have two options:
1. For each fetched movie, you'll have to emit another request to fetch the genre and director object/document.
2. using populate() method in the API project, you can preload the genre & director objects and include it in the movie object. The second options is easier and cleaner to implement but it's on the API side.
https://medium.com/@nicknauert/mongooses-model-populate-b844ae6d1ee7

2024-08-13 15:02 UTC, ibxibx commented on src/components/main-view/main-view.jsx
> +            director: movie.Director.Name,
Thank you, implementing

2024-08-14 18:17 UTC, stratospherique requested changes
There is a great mismatch between the movie object defined in the main-view component and the expected movie object in the child component. Please check the comments below.

Example: `movie.Title` won't work because in main-view, you parse the `Title` attributes to the movie object and named it `title`(lowercased). React will break and considers it a runtime error.

2024-08-14 18:17 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +            genres: movie.Genres.map((g) => g.genre),
genres here will be an array of strings(genre names). That means that the proptype as it was defined in movie-card and movie-view components is incorrect. they are expecting an array of objects.

2024-08-14 18:17 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +            genres: movie.Genres.map((g) => g.genre),
"genres" attribute is named with lowercase format where as the proptype on the movie-card & movie-view components is expecting `Genres`(CamelCased).

2024-08-14 18:17 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +            genres: movie.Genres.map((g) => g.genre),
The attributes names don't match. Neither their types. Please pay close attention

2024-08-14 18:17 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +            director: movie.Director.name, // Note: changed from Name to name
The same goes for director and the remaining of the attributes

2024-08-14 18:49 UTC, merged