Verified and corrected proptypes and naming conventions in all 3 comp…
ibxibx/mymdb pull request #11
Opened 2024-08-14 18:54 UTC by ibxibx

double-checked the correct proptypes and naming conventions

2024-08-14 23:00 UTC, stratospherique requested changes

2024-08-14 23:00 UTC, stratospherique commented on src/components/movie-view/movie-view.jsx
> -
This line shouldn't be removed. It's causing the app to break.

Check the proptype definition section in the bottom. There is usage of `PropTypes` class. Therefore, it should be imported at the top of the script.

2024-08-14 23:00 UTC, stratospherique commented on src/components/movie-view/movie-view.jsx
> +      birthYear: PropTypes.number.isRequired,
If you check the browser's devtool > console tab, you'll notice a runtime warning displayed about birthYear being expected but received as undefined. It means the the birthYear of the director in movie object is either unexistant or nil. Please make sure to know your data and properly define the proptypes.

2024-08-15 12:27 UTC, ibxibx commented on src/components/movie-view/movie-view.jsx
> -
Yes, I've put it back.

2024-08-15 12:27 UTC, ibxibx commented on src/components/movie-view/movie-view.jsx
> +      birthYear: PropTypes.number.isRequired,
Solved the issue.

2024-08-15 22:43 UTC, merged