Restructured to orig structure, changed readme doc
ibxibx/mymdb pull request #9
Opened 2024-08-08 18:35 UTC by ibxibx

2024-08-08 19:30 UTC, stratospherique requested changes
The server is not compiling because of the import statement on movie-card and movie-view files when you try to import components. Kindly delete them.

For example on movie-view.jsx, you can not add instruction like: `import MovieView from "./movie-view";` You're already defining a component named Movie-View, There is no need to import one from outside.

2024-08-08 19:30 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +import { MovieView } from "../movie-view/movie-view";
The Brackets here will make the import statement incorrect and cause the app's server to fail on compile.
The two files contain default export so you cannot use brackets.

2024-08-10 13:04 UTC, ibxibx reviewed
reviewed the changes

2024-08-10 22:21 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +import { MovieView } from "../movie-view/movie-view";
Here you didn't apply my suggestions about imports. I also provided an article explaining how it works. Please pay close attention

2024-08-10 22:37 UTC, stratospherique commented
- The proptypes definition for the movie-view and movie-card is incorrect. The name of the passed prop and its attributes should have the same name in the proptypes definition(same name and its case-sensitive)
  - For example, in main-view, the movie object was defined to contain an attribute called `genre`, but in the movie-card you defined the movie prop to expect a movie object that contains an attribute called `GenreID`(totally different).

2024-08-12 13:31 UTC, merged